### ISSUE TITLE
Checking "Check all" for modules breaks State

### ISSUE THREAD

**Issue by ddalcino** [ddalcino/aqt-list-server#10]
Checking "Check all" for modules alters State in a way that turns Module objects into String objects, which breaks output in the "Copy to Clipboard" section.

The result of this is that the "Your [jurplel/install-qt-action](https://github.com/jurplel/install-qt-action) yml:" and "Your [aqt install](https://github.com/miurahr/aqtinstall) command:" output sections, which the program suggests that you copy into your GitHub workflow or your terminal, prints the wrong thing. The "modules" section turns into a list of module descriptions, and not the names of the modules, resulting in a broken aqtinstall command.

**Example:**

The correct command:
```yaml
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==2.1.*'
        version: '6.5.0'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        modules: all
```
... becomes:
```yaml
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==2.1.*'
        version: '6.5.0'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        modules: 'Qt 3D Module for macOS Qt Charts for macOS Qt Connectivity for macOS Qt Data Visualization for macOS Qt Protobuf and Qt GRPC for macOS Qt HTTP Server for macOS Qt Image Formats for macOS Qt language Server for macOS Qt Location Qt Lottie Animation for macOS Qt Multimedia for macOS Qt Network Authorization for macOS Qt PDF for macOS Qt Positioning for macOS Quick: 3D Physics for macOS Qt Quick Effect Maker Qt Remote Objects for macOS Qt State Machine for macOS Qt Sensors for macOS Qt SerialBus for macOS Qt SerialPort for macOS Qt Speech for macOS Qt Virtual Keyboard for macOS Qt WebChannel for macOS Qt WebEngine for macOS Qt WebSockets for macOS Qt WebView for macOS Desktop Clang 64-bit Debug Information Files Qt 5 Compatibility Module for macOS Qt Quick 3D for macOS Qt Quick Timeline for macOS Qt Shader Tools for macOS'
```
