### ISSUE TITLE
jurplel/install-qt-action yml doesn't work

### ISSUE THREAD

**Issue by tim-gromeyer** [ddalcino/aqt-list-server#18]
Hello,
thank you for this amazing project!
After I selected everything I need it generates me following jurpel/install-qt-action yml:
```yml
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.5.0'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        modules: 'qtimageformats qtmultimedia qtspeech'
```

but this doesn't work. I'll fail with following error:
```
RROR: Cannot install aqtinstall==3.1.0, aqtinstall==3.1.1, aqtinstall==3.1.2, aqtinstall==3.1.3 and py7zr==0.19.* because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested py7zr==0.19.*
    aqtinstall 3.1.3 depends on py7zr>=0.20.2
    The user requested py7zr==0.19.*
    aqtinstall 3.1.2 depends on py7zr>=0.20.2
    The user requested py7zr==0.19.*
    aqtinstall 3.1.1 depends on py7zr>=0.20.2
    The user requested py7zr==0.19.*
    aqtinstall 3.1.0 depends on py7zr>=0.20.2
```

This is because by default `jurplel/install-qt-action` uses `py7zr==0.19.*` but aqlinstall needs `py7zr>=0.20.2` or above.  
By adding `        py7zrversion: '>=0.20.2'` to the workflow the error gets fixed.
